version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless
      - npm install -g yarn

  pre_build:
    commands:
      - echo "Authenticating with Serverless Framework..."
      - serverless login --provider aws --key $SERVERLESS_ACCESS_KEY
      - echo "Installing dependencies..."
      - cd layer/nodejs
      - yarn install --production
      - cd ../..

  build:
    commands:
      - echo "Packaging and deploying with Serverless Framework..."
      - >
        serverless deploy --stage $STAGE --region $REGION 
        --param="apiKeySecret=${API_KEY_SECRET}" 
        --verbose

artifacts:
  files:
    - '**/*'
  base-directory: .serverless

cache:
  paths:
    - 'layer/nodejs/node_modules/**/*'
