version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless@4.4.1
      - npm install -g yarn@1.22.22

  pre_build:
    commands:
      - echo "Authenticating with Serverless Framework..."
      - echo "SERVERLESS_ACCESS_KEY value: $SERVERLESS_ACCESS_KEY"
      - serverless login
      - echo "Installing dependencies..."
      - cd layer/nodejs
      - yarn install --production
      - cd ../..

  build:
    commands:
      - echo "Packaging and deploying with Serverless Framework..."
      - >
        serverless deploy --stage $STAGE --region $REGION 
        --param="apiKeySecret=${API_KEY_SECRET}" 
        --verbose

artifacts:
  files:
    - '**/*'
  base-directory: .serverless

cache:
  paths:
    - 'layer/nodejs/node_modules/**/*'
