service: serverless

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  deploymentBucket:
    name: serverless-framework-email-reminder-deployment-bucket
  environment:
    EVENTBRIDGE_ROLE_ARN: !GetAtt EventBridgeRole.Arn
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:logs'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'log-group:/aws/lambda/*:*:*'
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: '*'
    - Effect: Allow
      Action:
        - events:PutRule
        - events:PutTargets
        - events:ListRules
        - events:ListTargetsByRule
      Resource: '*'
    - Effect: Allow
      Action:
        - scheduler:CreateSchedule
        - scheduler:DeleteSchedule
        - scheduler:GetSchedule
        - scheduler:ListSchedules
        - scheduler:UpdateSchedule
      Resource: '*'
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource: !GetAtt EventBridgeRole.Arn
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: !Ref ApiKeySecret

package:
  individually: true

layers:
  commonDependencies:
    path: layer
    name: ${self:service}-${opt:stage, self:provider.stage}-common-dependencies
    description: Common dependencies for all functions
    compatibleRuntimes:
      - nodejs20.x
    retain: false

functions:
  authorizer:
    handler: src/functions/authorizer.handler
    name: AuthorizerFunction
    environment:
      API_KEY_SECRET_NAME: !Ref ApiKeySecret
    logRetentionInDays: 7
    layers:
      - { Ref: CommonDependenciesLambdaLayer }
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/authorizer.js
  sendMail:
    name: SendMailFunction
    handler: src/functions/sendMail.handler
    timeout: 10
    events:
      - http:
          path: send-mail
          method: post
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: request
    logRetentionInDays: 7
    layers:
      - { Ref: CommonDependenciesLambdaLayer }
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/sendMail.js

  emailReminder:
    handler: src/functions/sendMailReminder.handler
    name: EmailReminderFunction
    timeout: 10
    logRetentionInDays: 7
    layers:
      - { Ref: CommonDependenciesLambdaLayer }
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/sendMail.js
        - ./src/functions/sendMailReminder.js

  createSchedules:
    handler: src/functions/createSchedules.handler
    name: CreateSchedulesFunction
    environment:
      EMAIL_SENDER_ARN: !GetAtt EmailReminderLambdaFunction.Arn
    timeout: 30
    events:
      - http:
          path: create-schedules
          method: post
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: request
    logRetentionInDays: 7
    layers:
      - { Ref: CommonDependenciesLambdaLayer }
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/createSchedules.js

  updateSchedule:
    handler: src/functions/updateSchedule.handler
    name: UpdateScheduleFunction
    environment:
      EMAIL_SENDER_ARN: !GetAtt EmailReminderLambdaFunction.Arn
    timeout: 15
    events:
      - http:
          path: update-schedule
          method: put
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: request
    logRetentionInDays: 7
    layers:
      - { Ref: CommonDependenciesLambdaLayer }
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/updateSchedule.js

  listSchedules:
    handler: src/functions/listSchedules.handler
    name: ListSchedulesFunction
    timeout: 20
    events:
      - http:
          path: list-schedules
          method: get
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: request
    logRetentionInDays: 7
    layers:
      - { Ref: CommonDependenciesLambdaLayer }
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/listSchedules.js

  deleteSchedule:
    handler: src/functions/deleteSchedule.handler
    name: DeleteScheduleFunction
    timeout: 15
    events:
      - http:
          path: delete-schedule
          method: delete
          cors: true
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: request
    logRetentionInDays: 7
    layers:
      - { Ref: CommonDependenciesLambdaLayer }
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/deleteSchedule.js

resources:
  Outputs:
    EmailReminderFunctionArn:
      Value: !GetAtt EmailReminderLambdaFunction.Arn
      Export:
        Name: EmailReminderFunctionArn
    ApiKeySecretArn:
      Value: !Ref ApiKeySecret
      Export:
        Name: ${self:service}-${self:provider.stage}-ApiKeySecretArn

  Resources:
    ApiKeySecret:
      Type: 'AWS::SecretsManager::Secret'
      Properties:
        Name: ${self:service}/${self:provider.stage}/api-key
        Description: 'API Key for the authorizer function'
        SecretString: ${param:apiKeySecret}
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.WWW-Authenticate: "'Basic'"
        ResponseTemplates:
          application/json: |
            {
              "message": "$context.authorizer.error"
            }
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${self:provider.stage}
        RetentionInDays: 7
    EventBridgeRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - events.amazonaws.com
                  - scheduler.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AllowLambdaInvoke
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:EmailReminderFunction
          - PolicyName: EventBridgeSchedulerPermissions
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - scheduler:CreateSchedule
                    - scheduler:DeleteSchedule
                    - scheduler:GetSchedule
                    - scheduler:ListSchedules
                    - scheduler:UpdateSchedule
                  Resource: '*'
