org: sheikfaridh
app: serverless
service: serverless-email-reminder

provider:
  name: aws
  runtime: nodejs20.x
  profile: email_reminder_profile
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  environment:
    EVENTBRIDGE_ROLE_ARN: !GetAtt EventBridgeRole.Arn
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:logs'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'log-group:/aws/lambda/*:*:*'
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: '*'
    - Effect: Allow
      Action:
        - events:PutRule
        - events:PutTargets
        - events:ListRules
        - events:ListTargetsByRule
      Resource: '*'
    - Effect: Allow
      Action:
        - scheduler:CreateSchedule
        - scheduler:DeleteSchedule
        - scheduler:GetSchedule
        - scheduler:ListSchedules
        - scheduler:UpdateSchedule
      Resource: '*'
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource: !GetAtt EventBridgeRole.Arn

package:
  individually: true

functions:
  sendMail:
    name: SendMailFunction
    handler: src/functions/sendMail.handler
    timeout: 10
    events:
      - http:
          path: send-mail
          method: post
          cors: true
    logRetentionInDays: 7
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/sendMail.js
        - ./node_modules/**
        - ./package.json

  emailReminder:
    handler: src/functions/sendMailReminder.handler
    name: EmailReminderFunction
    timeout: 10
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/sendMail.js
        - ./src/functions/sendMailReminder.js
        - ./node_modules/**
        - ./package.json

  createSchedules:
    handler: src/functions/createSchedules.handler
    name: CreateSchedulesFunction
    environment:
      EMAIL_SENDER_ARN: !GetAtt EmailReminderLambdaFunction.Arn
    timeout: 20
    events:
      - http:
          path: create-schedules
          method: post
          cors: true
    logRetentionInDays: 7
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/createSchedules.js
        - ./node_modules/**
        - ./package.json

  updateSchedule:
    handler: src/functions/updateSchedule.handler
    name: UpdateScheduleFunction
    environment:
      EMAIL_SENDER_ARN: !GetAtt EmailReminderLambdaFunction.Arn
    timeout: 15
    events:
      - http:
          path: update-schedule
          method: put
          cors: true
    logRetentionInDays: 7
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/updateSchedule.js
        - ./node_modules/**
        - ./package.json

  listSchedules:
    handler: src/functions/listSchedules.handler
    name: ListSchedulesFunction
    timeout: 20
    events:
      - http:
          path: list-schedules
          method: get
          cors: true
    logRetentionInDays: 7
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/listSchedules.js
        - ./node_modules/**
        - ./package.json

  deleteSchedule:
    handler: src/functions/deleteSchedule.handler
    name: DeleteScheduleFunction
    timeout: 15
    events:
      - http:
          path: delete-schedule
          method: delete
          cors: true
    logRetentionInDays: 7
    package:
      exclude:
        - './**'
      include:
        - ./src/functions/deleteSchedule.js
        - ./node_modules/**
        - ./package.json

resources:
  Outputs:
    EmailReminderFunctionArn:
      Value: !GetAtt EmailReminderLambdaFunction.Arn
      Export:
        Name: EmailReminderFunctionArn

  Resources:
    LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:service}-${self:provider.stage}
        RetentionInDays: 7
    EventBridgeRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - events.amazonaws.com
                  - scheduler.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AllowLambdaInvoke
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:EmailReminderFunction
          - PolicyName: EventBridgeSchedulerPermissions
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - scheduler:CreateSchedule
                    - scheduler:DeleteSchedule
                    - scheduler:GetSchedule
                    - scheduler:ListSchedules
                    - scheduler:UpdateSchedule
                  Resource: '*'
